# Generated by Django 5.1.6 on 2025-03-07 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_indexer_web_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='block',
            old_name='hash',
            new_name='block_hash',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='tx_count',
            new_name='tx_num',
        ),
    ]
