# Generated by Django 5.1.6 on 2025-03-07 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_indexer_web_app', '0002_rename_hash_block_block_hash_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'managed': False},
        ),
    ]
