# Generated by Django 5.1.6 on 2025-03-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_indexer_web_app', '0003_alter_block_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='block',
            table='blocks',
        ),
    ]
